# Generated by Django 6.0.6 on 2026-06-21 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("materials", "0001_initial"),
        ("schools", "0002_storageusage"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "learning path",
                "verbose_name_plural": "learning paths",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("material", "Study Material"),
                            ("exam", "Take Exam"),
                            ("topic_review", "Review Topic"),
                            ("practice", "Practice Exercise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="analytics.learningpath",
                    ),
                ),
                (
                    "related_exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.exam",
                    ),
                ),
                (
                    "related_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materials.material",
                    ),
                ),
                (
                    "related_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subjects.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "learning path step",
                "verbose_name_plural": "learning path steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SchoolAnalytics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("total_teachers", models.IntegerField(default=0)),
                ("total_subjects", models.IntegerField(default=0)),
                ("total_exams_created", models.IntegerField(default=0)),
                (
                    "average_pass_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("storage_used_bytes", models.BigIntegerField(default=0)),
                ("ai_credits_used", models.IntegerField(default=0)),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="schools.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_analytics",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "school analytics",
                "verbose_name_plural": "school analytics",
                "ordering": ["-last_calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("question_generation", "Question Generation"),
                            ("essay_grading", "Essay Grading"),
                            ("tutoring", "AI Tutoring"),
                            ("content_creation", "Content Creation"),
                            ("summarization", "Summarization"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("credits_consumed", models.IntegerField(default=1)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("model_used", models.CharField(max_length=50)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI usage record",
                "verbose_name_plural": "AI usage records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "created_at"], name="idx_ai_usage_school_date"
                    ),
                    models.Index(
                        fields=["school", "usage_type"], name="idx_ai_usage_school_type"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentAnalytics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_exams_taken", models.IntegerField(default=0)),
                ("total_materials_completed", models.IntegerField(default=0)),
                ("total_time_spent_minutes", models.IntegerField(default=0)),
                (
                    "attendance_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rank_in_class", models.IntegerField(blank=True, null=True)),
                (
                    "improvement_trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_analytics",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_analytics",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "student analytics",
                "verbose_name_plural": "student analytics",
                "unique_together": {("student", "school", "term")},
            },
        ),
        migrations.CreateModel(
            name="SubjectAnalytics",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pass_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                (
                    "highest_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "lowest_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_analytics",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="subjects.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_analytics",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject analytics",
                "verbose_name_plural": "subject analytics",
                "unique_together": {("subject", "school", "term")},
            },
        ),
    ]
