# Generated by Django 6.0.6 on 2026-06-21 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_storageusage"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("link", "External Link"),
                            ("scorm", "SCORM Package"),
                            ("interactive", "Interactive"),
                            ("image", "Image"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="External link URL", null=True
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration for video/audio in seconds",
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="subjects.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="schools.term",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="subjects.topic",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialBookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="materials.material",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "material bookmark",
                "verbose_name_plural": "material bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="materials.material",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="materials.materialcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "material comment",
                "verbose_name_plural": "material comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                (
                    "last_position",
                    models.IntegerField(
                        default=0, help_text="Last position in seconds for video/audio"
                    ),
                ),
                ("completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.IntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="materials.material",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "material progress",
                "verbose_name_plural": "material progress records",
            },
        ),
        migrations.CreateModel(
            name="MaterialRating",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField(help_text="Rating from 1 to 5")),
                ("review", models.TextField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="materials.material",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "material rating",
                "verbose_name_plural": "material ratings",
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["school", "subject", "is_published"],
                name="idx_material_school_subj_pub",
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["school", "material_type"], name="idx_material_school_type"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="materialbookmark",
            unique_together={("student", "material")},
        ),
        migrations.AddIndex(
            model_name="materialprogress",
            index=models.Index(
                fields=["student", "completed"], name="idx_progress_student_complete"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="materialprogress",
            unique_together={("student", "material")},
        ),
        migrations.AlterUniqueTogether(
            name="materialrating",
            unique_together={("student", "material")},
        ),
    ]
