# Generated by Django 6.0.6 on 2026-06-23 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverificationtoken_passwordresettoken"),
        ("schools", "0005_phase7a_school_type_branding"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(
                        blank=True,
                        help_text="School-assigned admission / registration number",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date_of_admission", models.DateField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/profile_pictures/"
                    ),
                ),
                ("home_address", models.TextField(blank=True, null=True)),
                (
                    "state_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nationality", models.CharField(default="Nigerian", max_length=100)),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "guardian_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "guardian_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "guardian_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "guardian_relationship",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Father, Mother, Uncle, Guardian",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("guardian_address", models.TextField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=5, null=True)),
                ("genotype", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Known allergies, conditions, or special needs",
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profiles",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student profile",
                "verbose_name_plural": "student profiles",
                "ordering": ["user__last_name", "user__first_name"],
                "indexes": [
                    models.Index(
                        fields=["school", "admission_number"],
                        name="idx_sp_school_admission",
                    )
                ],
                "unique_together": {("user", "school")},
            },
        ),
    ]
