# Generated by Django 6.0.6 on 2026-06-21 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_storageusage"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("test", "Test"),
                            ("midterm", "Midterm Exam"),
                            ("final", "Final Exam"),
                            ("assignment", "Assignment"),
                            ("practice", "Practice"),
                        ],
                        db_index=True,
                        default="test",
                        max_length=20,
                    ),
                ),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("pass_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Duration in minutes. 0 means no time limit."
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the exam becomes available",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="When the exam closes", null=True
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_proctored", models.BooleanField(default=False)),
                ("shuffle_questions", models.BooleanField(default=False)),
                ("shuffle_options", models.BooleanField(default=False)),
                ("show_results_immediately", models.BooleanField(default=True)),
                ("show_correct_answers", models.BooleanField(default=True)),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of attempts allowed. -1 for unlimited.",
                    ),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific class this exam is for. Null means all enrolled students.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exams",
                        to="schools.classroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="subjects.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam",
                "verbose_name_plural": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("timed_out", "Timed Out"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "proctoring_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Proctoring events: tab switches, face detection, etc.",
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0, help_text="Total time spent in seconds"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exams.exam",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="Denormalized for efficient school-level queries",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "exam attempt",
                "verbose_name_plural": "exam attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "exams",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="exams.exam"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_groups",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam group",
                "verbose_name_plural": "exam groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "structure",
                    models.JSONField(
                        default=dict,
                        help_text='Template structure: {"sections": [{"name": "MCQ", "question_count": 20, "marks_per_question": 2, "type": "mcq"}]}',
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_templates",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam template",
                "verbose_name_plural": "exam templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_banks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "question bank",
                "verbose_name_plural": "question banks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("fill_blank", "Fill in the Blank"),
                            ("matching", "Matching"),
                        ],
                        db_index=True,
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(help_text="The question text")),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation shown after answering",
                        null=True,
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Marks allocated for this question",
                        max_digits=5,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="questions/images/"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (AI generation info, difficulty score, etc.)",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
                (
                    "question_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="exams.questionbank",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="questions/options/"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question option",
                "verbose_name_plural": "question options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True,
                        help_text="For short answer, essay, and fill-in-the-blank questions",
                        null=True,
                    ),
                ),
                (
                    "marks_awarded",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated feedback for the answer",
                        null=True,
                    ),
                ),
                (
                    "teacher_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Teacher feedback for the answer",
                        null=True,
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.examattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_in_answers",
                        to="exams.questionoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "answer",
                "verbose_name_plural": "answers",
                "ordering": ["question__order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("difficulty", "Difficulty Level"),
                            ("bloom_taxonomy", "Bloom Taxonomy"),
                            ("topic", "Topic"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "question tag",
                "verbose_name_plural": "question tags",
                "ordering": ["tag_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="exams.questiontag"
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "total_possible",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="Letter grade (A, B, C, etc.)",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific exam this result is from (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="exams.exam",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="subjects.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "result",
                "verbose_name_plural": "results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["school", "subject", "term"], name="idx_exam_school_subj_term"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["school", "is_published"], name="idx_exam_school_published"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["start_time", "end_time"], name="idx_exam_time_window"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "student", "status"], name="idx_attempt_exam_student"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["school", "submitted_at"], name="idx_attempt_school_submitted"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student", "status"], name="idx_attempt_student_status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("attempt", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="questiontag",
            unique_together={("school", "name", "tag_type")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["exam", "order"], name="idx_question_exam_order"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_bank", "question_type"], name="idx_question_bank_type"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["student", "term"], name="idx_result_student_term"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["school", "subject", "term"], name="idx_result_school_subj_term"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["school", "is_published"], name="idx_result_school_published"
            ),
        ),
    ]
