# Generated by Django 6.0.6 on 2026-06-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="allow_review",
            field=models.BooleanField(
                default=True,
                help_text="Allow students to review answers after submission",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="duration_minutes",
            field=models.IntegerField(default=60, help_text="Exam duration in minutes"),
        ),
        migrations.AlterField(
            model_name="exam",
            name="max_attempts",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of attempts allowed (0 = unlimited)",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="passing_score",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Minimum score percentage to pass",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="examanswer",
            name="selected_answer",
            field=models.CharField(
                blank=True,
                help_text="The answer selected/entered by the student",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Score as percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Raw score (marks obtained)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                help_text='For MCQ: "A", "B", "C", or "D". For True/False: "True" or "False".',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Explanation shown after submission", null=True
            ),
        ),
    ]
