# Generated by Django 6.0.6 on 2026-06-22 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_add_missing_fields"),
        ("schools", "0003_phase6a_academic_structure"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("school_exam", "School Exam"),
                            ("waec", "WAEC"),
                            ("neco", "NECO"),
                            ("jamb", "JAMB (UTME)"),
                            ("bece", "BECE"),
                            ("nabteb", "NABTEB"),
                            ("mock", "Mock Exam"),
                            ("practice", "Practice / Revision"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Public exam categories (WAEC, NECO, JAMB…) are shared across all schools.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "exam category",
                "verbose_name_plural": "exam categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all teachers in the school can use this bank.",
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target class level (JSS1–SSS3)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_banks",
                        to="schools.classlevel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_question_banks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_banks",
                        to="exams.examcategory",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_banks",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "question bank",
                "verbose_name_plural": "question banks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="exams.questioncategory",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "question category",
                "verbose_name_plural": "question categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex colour for UI display, e.g. #6366f1",
                        max_length=7,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "question tag",
                "verbose_name_plural": "question tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                        ],
                        db_index=True,
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("option_a", models.CharField(blank=True, max_length=500, null=True)),
                ("option_b", models.CharField(blank=True, max_length=500, null=True)),
                ("option_c", models.CharField(blank=True, max_length=500, null=True)),
                ("option_d", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "correct_answer",
                    models.CharField(
                        help_text='MCQ: "A"/"B"/"C"/"D". True/False: "True"/"False". Short answer: the expected answer.',
                        max_length=500,
                    ),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("marks", models.PositiveSmallIntegerField(default=1)),
                (
                    "exam_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Year the question appeared in a public exam (e.g. 2019)",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image/diagram for the question",
                        null=True,
                        upload_to="question_images/",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times this question has been added to an exam",
                    ),
                ),
                (
                    "import_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of import: csv, excel, manual, etc.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "import_batch",
                    models.CharField(
                        blank=True,
                        help_text="Batch identifier for bulk imports",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_questions",
                        to="subjects.topic",
                    ),
                ),
                (
                    "exam_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_questions",
                        to="exams.examcategory",
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_questions",
                        to="exams.questionbank",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_questions",
                        to="exams.questioncategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bank_questions",
                        to="exams.questiontag",
                    ),
                ),
            ],
            options={
                "verbose_name": "bank question",
                "verbose_name_plural": "bank questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamBankQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                ("question_type", models.CharField(max_length=20)),
                ("option_a", models.CharField(blank=True, max_length=500, null=True)),
                ("option_b", models.CharField(blank=True, max_length=500, null=True)),
                ("option_c", models.CharField(blank=True, max_length=500, null=True)),
                ("option_d", models.CharField(blank=True, max_length=500, null=True)),
                ("correct_answer", models.CharField(max_length=500)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("difficulty", models.CharField(max_length=10)),
                ("marks", models.PositiveSmallIntegerField(default=1)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bank_question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_links",
                        to="exams.bankquestion",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_question_links",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "exam bank question",
                "verbose_name_plural": "exam bank questions",
                "ordering": ["order", "created_at"],
                "unique_together": {("exam", "bank_question")},
            },
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["school", "subject"], name="idx_qbank_school_subject"
            ),
        ),
        migrations.AddIndex(
            model_name="questionbank",
            index=models.Index(
                fields=["school", "is_active"], name="idx_qbank_school_active"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questioncategory",
            unique_together={("school", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="questiontag",
            unique_together={("school", "name")},
        ),
        migrations.AddIndex(
            model_name="bankquestion",
            index=models.Index(fields=["bank", "difficulty"], name="idx_bq_bank_diff"),
        ),
        migrations.AddIndex(
            model_name="bankquestion",
            index=models.Index(
                fields=["bank", "question_type"], name="idx_bq_bank_type"
            ),
        ),
        migrations.AddIndex(
            model_name="bankquestion",
            index=models.Index(fields=["bank", "is_active"], name="idx_bq_bank_active"),
        ),
        migrations.AddIndex(
            model_name="bankquestion",
            index=models.Index(fields=["bank", "topic"], name="idx_bq_bank_topic"),
        ),
        migrations.AddIndex(
            model_name="bankquestion",
            index=models.Index(
                fields=["exam_category", "exam_year"], name="idx_bq_cat_year"
            ),
        ),
    ]
