# Generated by Django 6.0.6 on 2026-06-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_phase6c_practice_mock_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexamsession',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Allocated time in minutes'),
        ),
        migrations.AlterField(
            model_name='mockexamsession',
            name='exam_category',
            field=models.ForeignKey(blank=True, help_text='e.g. WAEC, NECO, JAMB — for context display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_exam_sessions', to='exams.examcategory'),
        ),
        migrations.AlterField(
            model_name='mockexamsession',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum percentage to pass', max_digits=5),
        ),
        migrations.AlterField(
            model_name='practiceanswer',
            name='selected_answer',
            field=models.CharField(blank=True, help_text='Answer submitted by the student', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='num_questions',
            field=models.PositiveSmallIntegerField(default=10, help_text='Number of questions selected for this session'),
        ),
        migrations.AlterField(
            model_name='topicperformance',
            name='accuracy_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Correct / Total * 100', max_digits=5),
        ),
    ]
