# Generated by Django 6.0.6 on 2026-06-23 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alternative phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("home_address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="parents/profile_pictures/"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-Employed"),
                            ("business", "Business Owner"),
                            ("civil_servant", "Civil Servant"),
                            ("retired", "Retired"),
                            ("unemployed", "Unemployed"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="NIN / Passport / Voter card number",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("receive_sms_alerts", models.BooleanField(default=True)),
                ("receive_email_alerts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "parent profile",
                "verbose_name_plural": "parent profiles",
            },
        ),
    ]
