# Generated by Django 6.0.6 on 2026-06-21 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_storageusage"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Referral code expiry date", null=True
                    ),
                ),
                (
                    "referred_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_by",
                        to="schools.school",
                    ),
                ),
                (
                    "referrer_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral",
                "verbose_name_plural": "referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("credit", "Account Credit"),
                            ("discount", "Subscription Discount"),
                            ("extension", "Subscription Extension"),
                            ("ai_credits", "AI Credits"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reward_value",
                    models.IntegerField(
                        help_text="Value depends on type: credit amount in NGN, discount %, days extension, or AI credits"
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Reward expiry date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referral",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward",
                        to="subscriptions.referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "referral reward",
                "verbose_name_plural": "referral rewards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extended_days",
                    models.IntegerField(
                        help_text="Number of days the trial was extended"
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for granting the extension"),
                ),
                (
                    "original_trial_end",
                    models.DateTimeField(help_text="Trial end date before extension"),
                ),
                (
                    "new_trial_end",
                    models.DateTimeField(help_text="Trial end date after extension"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_trial_extensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_extensions",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "trial extension",
                "verbose_name_plural": "trial extensions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("upgrade", "Upgrade"), ("downgrade", "Downgrade")],
                        max_length=10,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        help_text="When the change should take effect"
                    ),
                ),
                (
                    "proration_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount to credit/charge for proration",
                        max_digits=10,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests_from",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "to_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_requests_to",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan change request",
                "verbose_name_plural": "plan change requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "status"],
                        name="idx_planchange_sub_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        db_index=True,
                        help_text='Feature identifier, e.g. "exams_created", "materials_uploaded", "ai_requests"',
                        max_length=50,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                (
                    "usage_limit",
                    models.IntegerField(default=-1, help_text="-1 for unlimited"),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "usage record",
                "verbose_name_plural": "usage records",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["school", "feature_key", "period_start"],
                        name="idx_usage_school_feature_period",
                    )
                ],
                "unique_together": {("school", "feature_key", "period_start")},
            },
        ),
    ]
