# Generated by Django 6.0.6 on 2026-06-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_referral_referralreward_trialextension_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usagerecord",
            new_name="idx_usage_sch_feat_period",
            old_name="idx_usage_school_feature_period",
        ),
    ]
