# Generated by Django 6.0.6 on 2026-06-21 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "used_bytes",
                    models.BigIntegerField(
                        default=0, help_text="Total storage used in bytes"
                    ),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0, help_text="Total number of files stored"
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_usage",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "storage usage",
                "verbose_name_plural": "storage usages",
            },
        ),
    ]
