# Generated by Django 6.0.6 on 2026-06-22 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_storageusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsettings",
            name="motto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="principal_name",
            field=models.CharField(
                blank=True,
                help_text="Full name of the school principal / head teacher",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="e.g. 2024/2025", max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_sessions",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "academic session",
                "verbose_name_plural": "academic sessions",
                "ordering": ["-start_date"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="current_session",
            field=models.ForeignKey(
                blank=True,
                help_text="The currently active academic session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_settings",
                to="schools.academicsession",
            ),
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS 1"),
                            ("JSS2", "JSS 2"),
                            ("JSS3", "JSS 3"),
                            ("SSS1", "SSS 1"),
                            ("SSS2", "SSS 2"),
                            ("SSS3", "SSS 3"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text='Custom display name, e.g. "Junior Secondary School 1". Leave blank to use the default.',
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("junior", "Junior Secondary"),
                            ("senior", "Senior Secondary"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Sort order (1=JSS1 … 6=SSS3)"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_levels",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "class level",
                "verbose_name_plural": "class levels",
                "ordering": ["order", "code"],
                "unique_together": {("school", "code")},
            },
        ),
        migrations.AddField(
            model_name="classroom",
            name="class_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classrooms",
                to="schools.classlevel",
            ),
        ),
        migrations.CreateModel(
            name="StudentClassAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("transferred", "Transferred"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="schools.academicsession",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="schools.classroom",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_class_assignments",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "student class assignment",
                "verbose_name_plural": "student class assignments",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "academic_session", "status"],
                        name="idx_sca_school_session_status",
                    ),
                    models.Index(
                        fields=["classroom", "status"], name="idx_sca_classroom_status"
                    ),
                ],
                "unique_together": {("student", "academic_session")},
            },
        ),
    ]
