# Generated by Django 6.0.6 on 2026-06-23 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_phase7a_school_registration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="primary_color",
            field=models.CharField(blank=True, default="#1A73E8", max_length=10),
        ),
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                choices=[
                    ("secondary_school", "Secondary School"),
                    ("tutorial_center", "Tutorial Center"),
                    ("cbt_center", "CBT Center"),
                ],
                db_index=True,
                default="secondary_school",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="secondary_color",
            field=models.CharField(blank=True, default="#FFFFFF", max_length=10),
        ),
        migrations.CreateModel(
            name="ParentStudentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        default="parent",
                        help_text="e.g. Father, Mother, Guardian",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="School admin who created this link",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_student_links",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "parent-student link",
                "verbose_name_plural": "parent-student links",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "parent", "status"],
                        name="idx_psl_school_parent",
                    ),
                    models.Index(
                        fields=["school", "student", "status"],
                        name="idx_psl_school_student",
                    ),
                ],
                "unique_together": {("school", "parent", "student")},
            },
        ),
    ]
