# Generated by Django 6.0.6 on 2026-06-23 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_phase7a_school_type_branding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview (Not Applied)"),
                            ("applied", "Applied"),
                            ("undone", "Undone"),
                        ],
                        db_index=True,
                        default="preview",
                        max_length=10,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_session",
                    models.ForeignKey(
                        help_text="Session students are being promoted FROM",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_from",
                        to="schools.academicsession",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_promotions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_promotions",
                        to="schools.school",
                    ),
                ),
                (
                    "to_session",
                    models.ForeignKey(
                        help_text="Session students are being promoted TO",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions_to",
                        to="schools.academicsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "class promotion",
                "verbose_name_plural": "class promotions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolBranding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/branding/logos/"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/branding/favicons/"
                    ),
                ),
                ("primary_color", models.CharField(default="#1A73E8", max_length=10)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=10)),
                ("accent_color", models.CharField(default="#F4B400", max_length=10)),
                ("motto", models.CharField(blank=True, max_length=255, null=True)),
                ("tagline", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "report_header_text",
                    models.TextField(
                        blank=True,
                        help_text="Text shown at the top of result sheets and report cards",
                        null=True,
                    ),
                ),
                (
                    "certificate_header_text",
                    models.TextField(
                        blank=True,
                        help_text="Text shown at the top of certificates",
                        null=True,
                    ),
                ),
                ("report_footer_text", models.TextField(blank=True, null=True)),
                ("certificate_footer_text", models.TextField(blank=True, null=True)),
                (
                    "principal_signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/branding/signatures/"
                    ),
                ),
                (
                    "stamp_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/branding/stamps/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "school branding",
                "verbose_name_plural": "school brandings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("student_created", "Student Created"),
                            ("student_updated", "Student Updated"),
                            ("student_deleted", "Student Deleted"),
                            ("teacher_created", "Teacher Created"),
                            ("teacher_updated", "Teacher Updated"),
                            ("teacher_deleted", "Teacher Deleted"),
                            ("parent_created", "Parent Created"),
                            ("parent_updated", "Parent Updated"),
                            ("parent_deleted", "Parent Deleted"),
                            ("parent_linked", "Parent Linked to Student"),
                            ("parent_unlinked", "Parent Unlinked from Student"),
                            ("exam_created", "Exam Created"),
                            ("exam_published", "Exam Published"),
                            ("exam_deleted", "Exam Deleted"),
                            ("result_modified", "Result Modified"),
                            ("result_published", "Result Published"),
                            ("class_promoted", "Class Promoted"),
                            ("class_promotion_undone", "Class Promotion Undone"),
                            ("school_settings_updated", "School Settings Updated"),
                            ("branding_updated", "School Branding Updated"),
                            ("member_added", "Member Added"),
                            ("member_removed", "Member Removed"),
                            ("bulk_import", "Bulk Import"),
                            ("document_generated", "Document Generated"),
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("password_changed", "Password Changed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text='Model name of the affected object, e.g. "User", "Exam"',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="PK of the affected object",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of the target",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for platform-level actions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "action", "created_at"],
                        name="idx_audit_school_action",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="idx_audit_actor"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="idx_audit_target"
                    ),
                ],
            },
        ),
    ]
