# Generated by Django 6.0.6 on 2026-06-21 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_storageusage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code, e.g. MATH101", max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "credit_units",
                    models.IntegerField(
                        default=1, help_text="Credit units/weight for this subject"
                    ),
                ),
                (
                    "is_elective",
                    models.BooleanField(
                        default=False, help_text="Whether this is an elective subject"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="schools.department",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject",
                "verbose_name_plural": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "minimum_grade",
                    models.CharField(
                        blank=True,
                        help_text='Minimum grade required, e.g. "C" or "50"',
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "required_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisite_for",
                        to="subjects.subject",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "prerequisite",
                "verbose_name_plural": "prerequisites",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("dropped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="schools.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="schools.term",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "enrollment",
                "verbose_name_plural": "enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassSubject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_compulsory",
                    models.BooleanField(
                        default=True,
                        help_text="Whether all students in this class must take this subject",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="schools.classroom",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="schools.term",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_subjects",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "class subject",
                "verbose_name_plural": "class subjects",
            },
        ),
        migrations.CreateModel(
            name="SubjectTeacherAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the primary teacher for this subject/class",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="schools.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject teacher assignment",
                "verbose_name_plural": "subject teacher assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "First Term 2025 Timetable"', max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="schools.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetables",
                        to="schools.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "timetable",
                "verbose_name_plural": "timetables",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetableSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "room_name",
                    models.CharField(
                        blank=True,
                        help_text="Physical room/location name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="schools.classroom",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_slots",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="subjects.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "timetable slot",
                "verbose_name_plural": "timetable slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within parent"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="subjects.topic",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "topics",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["school", "is_active"], name="idx_subject_school_active"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["school", "department"], name="idx_subject_school_dept"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="prerequisite",
            unique_together={("subject", "required_subject")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "term", "status"], name="idx_enrollment_student_term"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["subject", "term", "status"], name="idx_enrollment_subject_term"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "subject", "term")},
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("classroom", "subject", "term")},
        ),
        migrations.AddIndex(
            model_name="subjectteacherassignment",
            index=models.Index(
                fields=["teacher", "term"], name="idx_assignment_teacher_term"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectteacherassignment",
            unique_together={("subject", "teacher", "classroom", "term")},
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["timetable", "day_of_week"], name="idx_slot_timetable_day"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["teacher", "day_of_week"], name="idx_slot_teacher_day"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["classroom", "day_of_week"], name="idx_slot_class_day"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["subject", "order"], name="idx_topic_subject_order"
            ),
        ),
    ]
